### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by JeronimoC23** [JeronimoC23/biblioteca-bayer-Django#19]
Sqlite3, es suficiente para la pag? deberia migrar a otra mejor?

**Comment by MJoaaquin** [comment]
https://www.digitalocean.com/community/tutorials/sqlite-vs-mysql-vs-postgresql-a-comparison-of-relational-database-management-systems

esta piola tiene una sección de cuando usar y cuando no usar postgres, mysql y sqlite. Yo no estoy seguro pero capaz te conviene usar algo como postgres :thinking:

**Comment by JeronimoC23** [comment]
Resuelto con postgre
